//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MittalSquash.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventId { get; set; }
        public string Name { get; set; }
        public System.DateTime EventDate { get; set; }
        public string EventTime { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UserId { get; set; }
        public int ResourceId { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Resource Resource { get; set; }
    }
}
