//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MittalSquash.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBlacklist
    {
        public string UserId { get; set; }
        public int RegisterId { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
